name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install Frontend Dependencies
      working-directory: ./
      run: npm install

    - name: Build Frontend
      working-directory: ./
      run: npm run build

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull latest code on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.211.206.227 << 'EOF'
          cd /var/www/frontend || exit
          git pull origin main || exit
        EOF
